spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/brevity_link_database
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.connect-retries=10
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

app.base-url=${APP_URL:http://localhost:8080/}

jwt.secret=${JWT_SECRET}
alphabet.secret=${ALPHABET_SECRET}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.links.prefix=links
